import random
import math
from environment import Agent, Environment
from planner import RoutePlanner
from simulator import Simulator


class LearningAgent(Agent):
    """ An agent that learns to drive in the Smartcab world.
        This is the object you will be modifying. """

    def __init__(self, env, learning = False, epsilon = 1.0, alpha = 0.5, decay_function = None):
        super(LearningAgent, self).__init__(env)     # Set the agent in the environment
        self.planner = RoutePlanner(self.env, self)  # Create a route planner
        self.valid_actions = self.env.valid_actions  # The set of valid actions

        # Set parameters of the learning agent
        self.learning = learning  # Whether the agent is expected to learn
        self.Q = dict()           # Create a Q-table which will be a dictionary of tuples
        self.epsilon = epsilon    # Random exploration factor
        self.alpha = alpha        # Learning factor

        # Additional parameters
        random.seed(42)
        self.t = 1                # Iteration number
        self.decay_function = decay_function
        self.testing = False

    def reset(self, destination = None, testing = False):
        """ The reset function is called at the beginning of each trial.
            'testing' is set to True if testing trials are being used
            once training trials have completed. """

        self.testing = testing

        # Select the destination as the new location to route to
        self.planner.route_to(destination)

        # Update epsilon using a decay function of your choice
        # Update additional class parameters as needed
        # If 'testing' is True, set epsilon and alpha to 0
        if testing:
            self.alpha = 0.0
            self.epsilon = 0.0
        else:
            self.epsilon = self.decay_function(self.t)
        self.t += 1

        return None

    def build_state(self):
        """ The build_state function is called when the agent requests data from the 
            environment. The next waypoint, the intersection inputs, and the deadline 
            are all features available to the agent. """

        # Collect data about the environment
        waypoint = self.planner.next_waypoint()  # The next waypoint
        inputs = self.env.sense(self)            # Visual input - intersection light and traffic
        deadline = self.env.get_deadline(self)   # Remaining deadline

        state = (waypoint, inputs["light"], inputs["oncoming"], inputs["left"])

        return state

    def get_maxQ(self, state):
        """ The get_maxQ function is called when the agent is asked to find the
            maximum Q-value of all actions based on the 'state' the smartcab is in. """

        max_q = max(map(lambda value_visits: value_visits[0], self.Q[state].values()))
        return max_q

    def createQ(self, state):
        """ The createQ function is called when a state is generated by the agent. """

        if state not in self.Q:
            self.Q[state] = {action: (0.0, 0) for action in self.valid_actions}

    def choose_action(self, state):
        """ The choose_action function is called when the agent is asked to choose
            which action to take, based on the 'state' the smartcab is in. """

        # Set the agent state and default action
        self.state = state
        self.next_waypoint = self.planner.next_waypoint()

        # When learning, choose a random action with 'epsilon' probability
        #   Otherwise, choose an action with the highest Q-value for the current state

        if self.learning:
            use_exploitation = random.uniform(0, 1) > self.epsilon
            max_q = self.get_maxQ(state)
            best_actions, other_actions = [], []
            for key, value in self.Q[state].iteritems():
                (other_actions, best_actions)[value[0] == max_q].append(key)
            action = random.choice(best_actions if use_exploitation or not other_actions else other_actions)
        else:
            action = random.choice(self.valid_actions)

        return action

    def learn(self, state, action, reward):
        """ The learn function is called after the agent completes an action and
            receives an award. This function does not consider future rewards 
            when conducting learning. """

        # When learning, implement the value iteration update rule
        #   Use only the learning rate 'alpha' (do not use the discount factor 'gamma')
        if self.learning:
            q = self.Q[state][action][0]
            visits = self.Q[state][action][1]
            self.Q[state][action] = (q + self.alpha * (reward - q), visits + 1 if not self.testing else visits)
        return

    def update(self):
        """ The update function is called when a time step is completed in the 
            environment for a given trial. This function will build the agent
            state, choose an action, receive a reward, and learn if enabled. """

        state = self.build_state()           # Get current state
        self.createQ(state)                  # Create 'state' in Q-table
        action = self.choose_action(state)   # Choose an action
        reward = self.env.act(self, action)  # Receive a reward
        self.learn(state, action, reward)    # Q-learn

        return
        

def run(simulation_index = 0):
    """ Driving function for running the simulation. 
        Press ESC to close the simulation, or [SPACE] to pause the simulation. """

    n_trials = 200

    def linear_decay(a):
        return lambda t: 1.0 - a * t

    def exponential_decay(a):
        return lambda t: a ** t

    def cos_decay(a):
        return lambda t: math.cos(a * t * math.pi / 2)

    def power_decay(t):
        return 1.0 / t ** 2

    def tanh_decay(a):
        return lambda t: 1.0 - math.tanh(a * t)

    def exp_decay(a):
        return lambda t: math.exp(- a * t)

    decay_functions = [
        linear_decay(a = 1.0 / n_trials),
        exponential_decay(a = 0.95),
        exponential_decay(a = 0.90),
        exponential_decay(a = 0.85),
        cos_decay(a = 1.0 / n_trials),
        power_decay,
        tanh_decay(a = 0.01),
        tanh_decay(a = 0.025),
        exp_decay(a = 0.01),
        exp_decay(a = 0.025)
    ]

    decay_function = decay_functions[simulation_index]

    ##############
    # Create the environment
    # Flags:
    #   verbose     - set to True to display additional output from the simulation
    #   num_dummies - discrete number of dummy agents in the environment, default is 100
    #   grid_size   - discrete number of intersections (columns, rows), default is (8, 6)
    env = Environment(verbose = True)
    
    ##############
    # Create the driving agent
    # Flags:
    #   learning   - set to True to force the driving agent to use Q-learning
    #    * epsilon - continuous value for the exploration factor, default is 1
    #    * alpha   - continuous value for the learning rate, default is 0.5
    agent = env.create_agent(LearningAgent, learning = True, alpha = 0.05, epsilon = 1, decay_function = decay_function)

    ##############
    # Follow the driving agent
    # Flags:
    #   enforce_deadline - set to True to enforce a deadline metric
    env.set_primary_agent(agent, enforce_deadline = True)

    ##############
    # Create the simulation
    # Flags:
    #   update_delay - continuous time (in seconds) between actions, default is 2.0 seconds
    #   display      - set to False to disable the GUI if PyGame is enabled
    #   log_metrics  - set to True to log trial and simulation results to /logs
    #   optimized    - set to True to change the default log file name
    sim = Simulator(env, update_delay = 0.001, display = False, log_metrics = True, log_file_index = simulation_index + 1, optimized = True)

    ##############
    # Run the simulator
    # Flags:
    #   tolerance  - epsilon tolerance before beginning testing, default is 0.05 
    #   n_test     - discrete number of testing trials to perform, default is 0
    sim.run(n_test = 100, tolerance = decay_function(n_trials))

if __name__ == '__main__':
    run()
